config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_conversation, only: [:index]
  
  def index
    @conversation = Conversation.last
    @manga = LibraryItem.last(4)
    @user = User.last(3)
    @most_wish = WishlistItem.all.group_by(&:manga_id).values.max_by(3) {|x| x.size }
    @most_lib = LibraryItem.all.group_by(&:manga_id).values.max_by(3) {|x| x.size }
    @discovery = LibraryItem.all.sample(3)
  end

  def search  
    if params[:search].blank?  
      redirect_to(mangas_path, alert: "Champ vide!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Manga.all.where("lower(title) LIKE :search", search: "%#{@parameter}%")
    end   
  end  

  def libsearch  

    if params[:search].blank? 
      redirect_to(library_items_path, alert: "Champ vide!") and return 
    else  
      @libparameter = params[:search].downcase   
      @items = []
      
      LibraryItem.all.each do |item|
        if (item.manga.title).include?(params[:search])
        @items << item
          end
        end       
    end 
  end
  
  private

  def set_conversation
    @conversation = Conversation.last
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_user?
  before_action :set_conversation, only: [:show]
    
 

  def show
    @user = User.find(params[:id])
    @user_collection = LibraryItem.where(user: current_user)
    @user_wishlist = WishlistItem.where(user: current_user)
  end

  def edit
    @user_collection = LibraryItem.where(user: current_user)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name])
      redirect_to '/'
    end
  end


  private
  
  def is_user?
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "action impossible !"
      redirect_to "/"
    end
  end

  def set_conversation
    @conversation = Conversation.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_card-user.html.erb
<div class="m-2 card-user-all">
  
  <% @user.each do |user|%>
  
    <div class="card-user">
      <%if user.avatar.attached?%>
        <%= image_tag user.avatar, class: "img-user" %>
      <% else %>
        <%= image_tag "kirua.jpg", class: "img-user" %>
      <%end%>
      <p class="card-time"><%= time_ago_in_words(user.created_at) %></p>
      <h4 class="card-title"><%= user.name %></h4>
    </div>
      
  <% end %>
  
</div>

app/views/static_pages/_card.html.erb
<div class="container-fluid mt-2">
	<div class="row m-2 card-all">
		<% @manga.each do |manga|%>
				
      <article class="card-last-manga card--1">
        <div class="card__img" style="background-image: url('<%= manga.manga.image_url %>')"></div>
        <a href="<%=library_item_path(manga)%>" class="card_link">
          <div class="card__img--hover" style="background-image: url('<%= manga.manga.image_url %>')"></div>
        </a>
        <div class="card__info">
           <%= link_to manga.manga.title.capitalize, library_item_path(manga), class: "card__title"%>
          <h5><span>par <%=manga.manga.author%></span></h5>
          <% manga.manga.categories.each do |category| %>
          <%= link_to category.name, category_path(category.id) %>
          <%end%>
        </div>
      </article>
				
		<% end %>
	</div>
</div>

app/views/static_pages/_list-home.html.erb
<a href="<%= manga_path(wish.first.manga)%>"><li class="list-home">
  <ul>
    <li>
      <%= image_tag wish.first.manga.image_url, class: "image-list" %>
    </li>
    <li class="position-num">
      <%= index + 1 %>
    </li>
    <li class="title-list">
      <%= wish.first.manga.title %>
    </li>
    <li>
      <blockquote><%= wish.first.manga.author %></blockquote>
    </li>
  </ul>
</a>

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navbar">
  <a href='<%= root_path%>' class="brand-link mr-4"><%= image_tag 'logo3.png', class:"brand", size: "60x60" %></a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Accueil", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Mangas", mangas_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Bibliothèque", library_items_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Concept", static_pages_concept_page_path, class: 'nav-link' %>
      </li>
    </ul>

      <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
      <% if user_signed_in?%>
        <% if current_user.name == "Guest" %>
              <li class="pt-2 mr-1"> <%= current_user.name %>
                <%= link_to "changer", edit_user_registration_path(current_user) %>
              </li>
        <% end  %>
        <% if current_user && current_user.is_admin == true%>
          <li class="nav-item active">
            <%= link_to "Admin dashboard", rails_admin_path, class:"nav-link" %>
          </li>
        <% end %>
          <li class="nav-item active">
          <% if @conversation != nil %>
            <a href='<%= conversation_messages_path(@conversation) %>' class='nav-link active' >Messages
              <% if !@conversation.unread_message_count(current_user).zero? %>
                (<%= @conversation.unread_message_count(current_user) %>)
              <% end %>
            </a>
          <% end %>
          </li>
        <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profil/Quitter
          </a>
          <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item menu-nav" <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>
            <a class="dropdown-item menu-nav" <%= link_to "Profil", user_path(current_user) %></a>
          </div>
        </li>
        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Se Connecter/S'inscrire
          </a>
          <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item menu-nav" href="<%=new_user_session_path%>">Se connecter</a>
            <a class="dropdown-item menu-nav" href="<%=new_user_registration_path%>">S'inscrire</a>
          </div>
        <% end %>
    </ul> 
  </div>
</nav>

app/views/static_pages/concept_page.html.erb
  <div class="row profile-banner p-5 d-flex justify-content-center align-items-center"><br>
    <div><h1 class="concept-title"> Découvrez Kasu</h1>
          <p class="text-center px-5 mx-5" style="font-size:25px"><b> Bienvenue dans la communauté de passionnés de manga. <br> Dévore tous les mangas à moindre coût grâce à l'échange.</b> </p>
        </div>
  </div>

        <!-- Molécule de présentation -->
        
  <div class="container">
    <h2 class="text-center m-5 p-5">Comment ça fonctionne ?</h2> 
    <div class='row px-5 align-items-center'>
      <div class='col-6 px-5'>
          <h3> Partage /Échange</h3>
        <p>Kasu est une plateforme d'échange qui te permet d'assouvir ta passion en échangeant tes Mangas contre d'autres. Rentres ton manga dans la bibliothèque, si une personne est intéressée par celui-ci, il prendra contact avec toi via la messagerie du site, vous pourrez alors vous mettre d'accord sur les modalité. Une fois d'accord,
            tu pourras confirmer l'échange et récupérer son Kasu point.</p>
      </div>
      <div class='col-4 pb-5'>
        <%= image_tag 'achete.png'%>
      </div>
    </div>
  
    <div class='row p-5 align-items-center'>
      <div class='col-4 px-5'>
        <%= image_tag 'recois.png'%>
      </div>
      <div class='col-6 px-5'>
        <h3>Reçois</h3>
        <p>Quand tu échanges un livre, tu reçois un Kasu point qui te permettra à ton tour d’acquérir un nouveau manga ensuite si tu le désires, soit tu gardes ce manga, soit tu le rentres dans la bibliothèque.</p>
      </div>
    </div>
    <div class='row px-5 align-items-center'>
      <div class='col-6 px-5'>
        <h3>Choisis</h3>
      <p>J'indique les livres que je possède en entrant simplement les mangas dans la bibliothèque ou en cliquant sur le bouton "ajouter un manga". Lorsqu'un membre souhaite un de mes livres, je lui expédie et je gagne 1 kasu Point par livre. Avec celui-ci je commande les livres que je désire.</p>
      </div>
      <div class='col-4 pb-5'>
      <%= image_tag 'echange.png'%>
    </div>
  </div>
</div>


<div class="not-in-list mt-3">
    <div class="opacity-not">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h3><b>Inscrivez-vous gratuitement, les 100 premiers inscrits recevront 1 Kasu Point !</b></h3>
    <a href="<%=new_user_registration_path%>" class="btn btn-danger">s'inscrire</a>
    </div>
  </div>

app/views/static_pages/index.html.erb
<header>
  <div class="container-fluid" id="fond">
    <%= image_tag 'rectangle1.png', class:"rectangle1 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rouge1.png', class:"rouge1 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rectangle2.png', class:"rectangle2 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle3.png', class:"rectangle3 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rectangle4.png', class:"rectangle4 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle5.png', class:"rectangle5 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rouge2.png', class:"rouge2 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle6.png', class:"rectangle6 animate__animated animate__fadeInUpBig"%>
    <div class="container-title animate__animated animate__fadeInLeftBig">
      <h1 class="title">La marketplace des mangas !</h1>
      <a class="btn btn-tercery" href="<%= mangas_path%>">Découvrez-les</a>
    </div>
  </div>
</header>

<div class="container d-flex justify-content-center">
 <%= render "shared/searchbar" %>
</div>

<main>
  <div class="d-flex justify-content-center">
    <h2 class="intro m-5 text-center">Rejoins la communauté Kasu et échange tes Mangas en toute simplicité</h2>
  </div>
  <div class="container-fluid section1">
    <div class="row d-flex justify-content-center">
      <div class="col-xs-12 col-md-3 m-2 text-center">
        <a class="text-center" href="<%= mangas_path %>"><%= image_tag 'echange.png', class:"icon-explication icon1 mb-4"%></a>
        <h3><a href='<%= mangas_path %>'class="home_title text-center">1. Créé ta Bibliothèque</a></b></h3>
        <p class="icon-text d-flex">Met en ligne les mangas que tu souhaites échanger. </p>
      </div>
      <div class="col-xs-12 col-md-3 m-2 text-center ">
        <a class="text-center " href="<%= library_items_path %>"><%= image_tag 'recois.png', class:"icon-explication icon1 mb-4"%></a>
        <h3> <a class="home_title text-center" href='<%= library_items_path %>'>2. Trouve des Mangas</a></b></h3>
        <p class="icon-text d-flex">Trouve le Manga de tes rêves ou ajoute-le à ta Wishlist.
      </div>
      <div class="col-xs-12 col-md-3 m-2 text-center">
        <a class="text-center" href="<%= library_items_path %>"><%= image_tag 'achete.png', class:"icon-explication icon1 mb-4"%></a>
        <h3><a class="home_title text-center" href='<%= mangas_path %>'>3. Echange</a></b></h3>
        <p class="icon-text d-flex">Reçois des "Matchs" par email et échange grâce au kasu points. </p> 
      </div>
    </div>
  </div>

  <div class="section2">
    <h2 class="text-center">Les derniers mangas ajoutés</h2>
    <div class="container d-flex justify-content-around">
      <%= render "card" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "Les mangas disponibles", library_items_path, class: 'btn btn-outline-dark'%>

    </div>
  </div>

  <div class="section5">
    <ul class="group-list-home">
      <li class="list-title">Les mangas les plus demandés</li>
      <% @most_wish.each_with_index do |wish, index| %>
        <%= render "list-home", wish: wish, index: index %>
      <% end %>
      </ul>
    <ul class="group-list-home">
      <li class="list-title">
        Les mangas les plus échangés
      </li>
      <% @most_lib.each_with_index do |wish, index| %>
   
        <%= render "list-home", wish: wish, index: index %>

      <% end %>
    </ul>
    <ul class="group-list-home">
      <li class="list-title">A découvrir</li>
      <% @discovery.each_with_index do |wish, index| %>
        <a href="<%= library_item_path(wish)%>"><li class="list-home">
          <ul>
            <li>
              <%= image_tag wish.manga.image_url, class: "image-list" %>
            </li>
            <li class="position-num">
              <%= index + 1 %>
            </li>
            <li class="cut title-list">
              <%= wish.manga.title %>
            </li>
            <li>
              <blockquote><%= wish.manga.author %></blockquote>
            </li>
          </ul>
        </a>
      <% end %>
    </ul>
  </div>

  <div class="section3">
  <div class="container">
    <h2 class="text-center">Les nouveaux membres</h2>
    <%= render "card-user" %>
    </div>
  </div>

  <div class="section4">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h4>Toi aussi rejoins la communauté et échange en toute simplicité !</h4>
    <a href="<%=new_user_registration_path%>" class="btn btn-danger">s'inscrire</a>
  </div>

</main>

app/views/static_pages/libsearch.html.erb
<div class="container-fluid">
  <div class="container-fluid research-title">
    <div class="opacity-img container-fluid">
    <h2 class="text-center">Voici le résultat de ta recherche</h2>  
    </div>
  </div>
  <div class="container mt-3 all-card-result"> 

          <% @items.each do |result| %>  
        
            <% if result.user != current_user %>
							<article class="card-manga card--1">
								<div class="card-img" style="background-image: url('<%= result.manga.image_url %>')"></div>
									<a href="<%= library_item_path(result) %>" class="card_link">
								<div class="card-img-hover" style="background-image: url('<%= result.manga.image_url %>')"></div>
								</a>
								<div class="card-info">
									<h3 class="card-title"><%= image_tag 'available.png', class:"available mb-1"%> <%= result.manga.title.capitalize %></h3>
									<blockquote class="volume-manga">Tome : <%= result.volume %></blockquote>
								
									<% result.manga.categories.each do |category| %>
									<%= link_to category.name, category_path(category.id), class:"block" %>
									<%end%>
                  	<blockquote class="the-user"><small>proposé par <%= result.user.name %></small></blockquote>
									<%= link_to "Voir son manga", library_item_path(result), class: 'btn btn-outline-secondary der'%>
								</div>
							</article>	
              <% end %>	
				
           <% end %>
    </div>
  </div>

  <div class="not-in-list mt-3">
    <div class="opacity-not">
      <%= image_tag "sig_up.png", class:"img-sign" %>
      <h3>Le manga que tu veux n'y est pas ? Ajoute-le à ta whishlist  </h5>
      <a href="<%=mangas_path%>" class="btn btn-primary">Construire ma wishlist </a>
    </div>
  </div>
</div>

app/views/static_pages/search.html.erb
<div class="container-fluid">
  <div class="container-fluid research-title">
    <h2 class="text-center">Voici le résultat de ta recherche</h2>  
  </div>
  <div class="container-fluid m-3 all-card-result">

    <% @results.each do |result| %>
      <article class="card-manga card--1">
        <div class="card-img" style="background-image: url('<%= result.image_url %>')"></div>
        <a href="<%= manga_path(result) %>" class="card_link">
          <div class="card-img-hover" style="background-image: url('<%= result.image_url %>')"></div>
        </a>
        <div class="card-info">
          <h3 class="card-title card-index">
          <%= image_tag 'available.png', class:"available"%><%= result.title.capitalize %></h3>
          <h5><blockquote class="block">par <%=result.author%></blockquote></h5>            
          <%= link_to "Voir le manga", manga_path(result), class: 'btn btn-outline-secondary der'%>
        </div>
      </article>	
    <% end %>
  </div>

  <div class="section5">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h3><b>Toi aussi rejoins la communauté et échange en toute simplicité !</b></h3>
    <a href="<%=new_user_registration_path%>" class="btn btn-danger">s'inscrire</a>
  </div>
</div>

app/views/static_pages/team_page.html.erb
<div class="container-fluid" id="fond"><br>
  <h1 class="text-center bl">Notre équipe de Developpeur</h1>
  <div class="container">
    <div class="row">
      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://i.pinimg.com/originals/e0/9e/7a/e09e7a95a3f9baacc28c1cf48400f9ea.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://i.pinimg.com/originals/e0/9e/7a/e09e7a95a3f9baacc28c1cf48400f9ea.jpg')"></div>
            <div class="card__info">
            <h3 class="card__title">Dylan</h3>
          </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://image.winudf.com/v2/image/Y29tLmdhbmFzZGV2Lmhpc29rYS53YWxscGFwZXJfc2NyZWVuXzJfMTUxNzAwNjI5OF8wMjA/screen-2.jpg?fakeurl=1&type=.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://image.winudf.com/v2/image/Y29tLmdhbmFzZGV2Lmhpc29rYS53YWxscGFwZXJfc2NyZWVuXzJfMTUxNzAwNjI5OF8wMjA/screen-2.jpg?fakeurl=1&type=.jpg')"></div>
            <div class="card__info">
                <h3 class="card__title">Youcef</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://images-na.ssl-images-amazon.com/images/I/716DAbx1UAL._AC_SL1185_.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://images-na.ssl-images-amazon.com/images/I/716DAbx1UAL._AC_SL1185_.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Stephen</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://besthqwallpapers.com/Uploads/30-9-2020/142350/thumb2-piccolo-4k-green-neon-lights-dragon-ball-warrior.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://besthqwallpapers.com/Uploads/30-9-2020/142350/thumb2-piccolo-4k-green-neon-lights-dragon-ball-warrior.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Jules</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://www.coque-unique.com/clothes/powerbank-large-kakashi-sharingan-white.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://www.coque-unique.com/clothes/powerbank-large-kakashi-sharingan-white.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Gaëtan</h3>
            </div>
        </div>
      </article>
    </div>
  </div>
</div>