config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/controllers/library_items_controller.rb
class LibraryItemsController < ApplicationController

    before_action :authenticate_user!

    def index
        @pagy, @items = pagy(LibraryItem.all, link_extra: 'class="pagy-cust"') 
        @categories = Category.all

        @all_libraries = []
        LibraryItem.all.each{|item| @all_libraries << item.manga.id}
    end
    
    def show
        @item = LibraryItem.find(params[:id])
    end
    
    def create
      
        @item = LibraryItem.create(user: current_user, manga_id:params[:manga_id], state_description: params[:library_item][:state_description], volume: params[:library_item][:volume])
        @all_wishlist = WishlistItem.where(manga_id: params[:manga_id])
        @all_wishlist.each do |item|
            UserMailer.match_email(item.user, @item).deliver_now
        end

        redirect_to user_path(current_user), success: "Manga ajouté de votre bibliothèque !"
    end

    def update
        @item = LibraryItem.find(params[:id])
        @conversation_sender = @item.conversations
        token = @conversation_sender[0].sender.token_state
        token -= 1
        current_user_token = current_user.token_state
        current_user_token +=1

        if current_user_token < 0
            current_user.update(token_state: 0)
        else
            current_user.update(token_state: current_user_token)
        end
        
        @conversation_sender[0].sender.update(token_state: token)
        UserMailer.transaction_email(@conversation_sender[0].sender, @item).deliver_now
        @item.destroy
        redirect_to '/', success: 'Echange réalisé avec succès !'
    end

    def destroy 
        @item = LibraryItem.find(params[:id])
        @item.destroy
        respond_to do |format|
            format.html { redirect_to '/users/' + current_user.id.to_s, danger: "Manga supprimé de votre bibliothèque !" }
            format.js {}
        end 
    end   
       
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_user?
  before_action :set_conversation, only: [:show]
    
 

  def show
    @user = User.find(params[:id])
    @user_collection = LibraryItem.where(user: current_user)
    @user_wishlist = WishlistItem.where(user: current_user)
  end

  def edit
    @user_collection = LibraryItem.where(user: current_user)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name])
      redirect_to '/'
    end
  end


  private
  
  def is_user?
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "action impossible !"
      redirect_to "/"
    end
  end

  def set_conversation
    @conversation = Conversation.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/library_items_helper.rb
module LibraryItemsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/library_items/_libraryItemsCard.html.erb
<div class="container d-flex justify-content-around">
  <div class="row justify-content-between">
    <div class="col-9 card-all">
      <% @items.each do |item|%>
      <% if item.user != current_user %>
        <article class="card-manga card--1">
          <div class="card-img" style="background-image: url('<%= item.manga.image_url %>')"></div>
            <a href="<%= library_item_path(item) %>" class="card_link">
          <div class="card-img-hover" style="background-image: url('<%= item.manga.image_url %>')"></div>
          </a>
          <div class="card-info">
            <h3 class="card-title"><%= image_tag 'available.png', class:"available mb-1"%> <%= item.manga.title.capitalize %></h3>
            <blockquote class="volume-manga">Tome : <%= item.volume %></blockquote>
          
            <% item.manga.categories.each do |category| %>
            <%= link_to category.name, category_path(category.id), class:"block" %>
            <%end%>
              <blockquote class="the-user"><small>proposé par <%= item.user.name %></small></blockquote>
            <%= link_to "Voir son manga", library_item_path(item), class: 'btn btn-outline-secondary der'%>
          </div>
        </article>	
        <% end %>	
      <% end %>
    </div>
    <div class="col-2 justify-content-around mt-5">
      <%= link_to 'all', root_path  %> <br>
      <% @categories.each do |category| %>                 
      <%= link_to category.name, category_path(category) %> <br>  
      <% end %>
    </div>
  </div>
</div>
<div class="container-fluid pagy-position mb-5">
  <%= pagy_nav(@pagy).html_safe%>
</div>

app/views/library_items/destroy.js.erb
document.querySelector('.library-<%= @item.id %>').remove();

app/views/library_items/index.html.erb
<div class="container-fluid"> 
  <div class="container-fluid manga-title-index mb-5">
    <div class="container-fluid opacity-img">
      <h2 class='text-center pt-5'>La Bibliothèque des utilisateurs </h2>
      <h4 class='text-center'> Sélectionne les Mangas disponibles à l'échange et fais ta demande auprès des possesseurs </h4>
      <%= render "shared/libsearchbar" %>
    </div>
  </div>

  <%= render 'libraryItemsCard'%>
  
</div> 

app/views/library_items/show.html.erb
<div class="container-fluid">
  <div class="container-fluid p-5 background-items">
    <div>
      <h2 class="text-center m-1"> 
        Le manga    <strong><%= @item.manga.title.capitalize %></strong> de <strong><%= @item.user.name %> </strong>
      </h2>
    </div>
    <div class="containers-item mt-5">
      <div class="mr-5">
        <img src="<%= @item.manga.image_url %>">
      </div>

      <div class="description-item ml-5">
        <div class="d-flex justify-content-between">
        <h3>Titre : <%= @item.manga.title %></h3>
        </div>
        <h3>Propriétaire : <%= @item.user.name %></h3>
        <h3>Tome : <%= @item.volume %></h3>
        <h4>Etat : <%= @item.state_description %></h4>
        <%= link_to 'Voir la description', manga_path(@item.manga), class: 'btn btn-outline-secondary'%>
        <% if current_user.token_state <= 0%>
          <p class="mt-4"><strong>Vous n'avez pas assez de kasu points pour une demande à <%= @item.user.name %>.</strong></p>
        <% else%>
          <% if current_user != @item.user %>
            <%= link_to 'Faire une demande', conversations_path(sender_id: current_user.id, receiver_id: @item.user.id, library_item_id: @item.id), method: :post, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container pt-5">
    <h2 class="text-center"> Les autres mangas de <%= @item.user.name %></h2>

    <div class="all-show-manga px-5">
      <% @item.user.library_items.each do |item| %>
        <% if item.manga.title != @item.manga.title %>

          <article class="card-show-item card--1">
            <div class="card__img" style="background-image: url('<%= item.manga.image_url %>')"></div>
            <a href="<%=library_item_path(item.id)%>" class="card_link">
              <div class="card__img--hover" style="background-image: url('<%= item.manga.image_url %>')"></div>
            </a>
            <div class="card__info">
              <h5 class="card__title"><%= item.manga.title %></h5>
              <h5 class="card__title">tome n° : <%= item.volume %></h5>
              <%= link_to "Voir", library_item_path(item.id), class:"btn btn-outline-secondary my-2" %>
            </div>
          </article>

        <% end  %>
      <% end %>
    </div>
  </div>
</div>